<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <ApplicationIcon>YSAudioPlayer.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="YSAudioPlayer.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="YSAudioPlayer.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="common">
      <HintPath>..\..\common-cs\common\bin\Release\net10.0-windows\common.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
